### ISSUE TITLE
MySQL Error Column 'topic_desc' can not be null [1048]

### ISSUE THREAD

**Issue by ghost** [GerB/cmbb#4]
Hello Developers,

I just test your extension in my PHPBB 3.2 forum at http://wpzweinull.ch/cms/phpbb32. Unfortunately it does not quite work.

A MySQL error is displayed when I create and submit an article. That looks so much.

```
SQL ERROR [ mysqli ]

Column 'topic_desc' cannot be null [1048]

SQL

INSERT INTO phpbb_topics (topic_poster, topic_time, topic_last_view_time, forum_id, icon_id, topic_posts_approved, topic_posts_softdeleted, topic_posts_unapproved, topic_visibility, topic_delete_user, topic_title, topic_first_poster_name, topic_first_poster_colour, topic_type, topic_time_limit, topic_attachment, topic_status, topic_desc) VALUES (2, 1485031929, 1485031929, '9', 0, 1, 0, 0, 1, 0, 'PHPBB 3.2 Extension cmbb als CMS für das Forum', 'Alex L', 'AA0000', 0, 0, 0, 0, NULL)
```

Unfortunately, no menu bar with categories is created in the Forum frontend. If I take the forum main URL as `/app.php/article/index`, there is nowhere in the forum a link to the forum index itself.

Forum index does not appear on the Articles main page.

Could you please check this again with you or fix the problem if necessary.

Thanks in advance.

**Comment by GerB** [comment]
Hi, thank you for reporting back.
It seems like you are using the Topic Description extension by RMcGirr: https://www.phpbb.com/customise/db/extension/topic_description/
Can you confirm that?

That extension requires an entry for the topic description on every created topic. 

Of course, cmBB cannot take every possible extension into account that does *something* on whatever functions cmBB uses and decide what to do when that particular extension may or may not be installed. That's not feasible. For now, I don't have an idea for a good approach.

I've checked the support tab for that extension, I see there are similar issues with other extensions: https://www.phpbb.com/customise/db/extension/topic_description/support/topic/165736
RMcGirr hasn't responded to it yet, and the issue is several months old. You could try and post there as well and link to this issue here. Feel free to quote me or send me a PM on phpBB.com to notify me when you do so.

As I see it, the easiest way would be for RMcGirr to add a default value '' (empty string) for the topic description to cope with any other extension that creates a topic. But I haven't studied his extension so I might be wrong.

**Comment by ghost** [comment]
Gladly that. I've now taken as a solution to my problem that I completely renounce on Topic Description. So it was possible for me to publish the first article.

I still have these problems!

How can I make sure that Articles Index thumbnails are displayed that were also uploaded when creating articles?

Also, I get a MySQLi error message, if the blog with the right sidebar two JS scripts are integrated.

It is called "data to long for this column in raw 1"

I've just added Google Adsense and another javascript widget. Unfortunately I will be shown a error message.

Can you please check this again with you.

Thanks in advance.

Check it out at http://wpzweinull.ch/cms/phpbb32/app.php/article/index times. The one JS script is displayed without problems. Two scripts do not work and generate an error message.

**Comment by GerB** [comment]
I think the MySQL error is caused by simply too much data to store in the default config table. I'll have to move that to config_text I guess, but I need to examine that further. Didn't need that yet, but I notice it for the first time now it's a bit tight. Thanks for bringing this up. 

Can you elaborate on this:

> How can I make sure that Articles Index thumbnails are displayed that were also uploaded when creating articles?

I don't quite understand what you're trying to say here. I see your avatar is displayed as expected so that's probably not what you mean.

**Comment by ghost** [comment]
Yes, it probably is. I'll wait until you commit the new changes here.

I thought the teaser thumbnails and no avatar is displayed. But well, that's fine.

Now something has been discovered and the script does not load with the image upload. Please take a look at the screenshot below.

![phpbb32-cmbb-image-upload-error](https://cloud.githubusercontent.com/assets/7885632/22253523/3ff50616-e252-11e6-8e5d-a073f12ef5d2.jpg)


I would like to upload an image in the Ckeditor from the hard disk and then go to the window with the picture upload. But unfortunately nothing is displayed there.

The images are at cmbb in **/cms/phpbb32/images/cmbb_upload**

If I examine it with Google Chrome Inspector, it says URL not found.

Is it perhaps because the whole forum is installed in the subdirectory?

CHMOD at the **/image** directory is set to 777. 755 should be enough however I think.

Would be great, if you can look at it.

Thanks in advance.

**Comment by GerB** [comment]
I just pushed a commit that should fix the MySQL error for the rightbar content. You can test it by uninstalling the extension, deleting the data and than install the current version from the master branche.

Can you please create a new issue about the image browser? Please also provide the link that Chrome inspector cannot found (e.g. what's included in the resulting page).

**Comment by GerB** [comment]
It seems you have solved this?

**Comment by ghost** [comment]
Yes, this problem is solved and you can close the issue.

**Comment by GerB** [comment]
Allright!
