### ISSUE TITLE
Image upload not worked - URL not found 404

### ISSUE THREAD

**Issue by ghost** [GerB/cmbb#5]
Here I have the problem that the image upload in the ckeditor does not work.

I click on the image tool in the editor and then go to the image upload. There everything is blank and only a few icons are displayed. See this screenshot.

![phpbb32-cmbb-image-upload-error](https://cloud.githubusercontent.com/assets/7885632/22255844/0d07bc6a-e259-11e6-8e51-88bfb9e300a6.jpg)

A URL for example would be like this: http://wpzweinull.ch/cms/phpbb32/images/cmbb_upload/2/1_phpbb32-froum-frontend-im-topic-wpzweinull-ch-gepostet-auf-internetblogger-de.jpg

In the forum frontend it says that this forum does not exist. But it is not a forum, but the directory with images for cmbb.

How can I solve the problem?

Thanks in advance.

**Comment by GerB** [comment]
The URL seems legit though. However, the message seems to indicate that there is a permissions issue. Can you double check if the file is actually there?

This probably is caused by a conflict with another extension. I see you have several of them installed (blog/download/directory/gallery).
Can you disable them one by one to check if it solves the problem? If you find it, please provide me a link to the specific extension.

If this is not the case, it might be caused by a .htaccess rule that is not standard. Do you have any edits in your .htaccess file or maybe one on a higher level than your forum root?

**Comment by ghost** [comment]
I took several hours to solve the problem. What exactly was that? In the directory **/cache**, I had to assign the directory **/production** CHMOD 777 and delete the contents of this directory.

Now I can upload pictures, which already worked before and also integrate them.

Amazing, but true. Sometimes the solution to a problem is so close, but I do not see it anyway. You never learn.

**Comment by GerB** [comment]
If I'm not mistaken, that folder should default always be 0777. Probably a glitch with your basic phpBB install.

Anyway, thanks for reporting back!
